#!/bin/sh

 # Check file sizes and remove largest.
if [ "$( stat -c '%s' "$1" )" -gt "$( stat -c '%s' "$2" )" ]; then
        # First file is larger
        printf 'Would remove "%s"\n' "$1"
        echo rm "$1"
        rm "$1"
else
        # Second file is larger, or same size
        printf 'Would remove "%s"\n' "$2"
        echo rm "$2"
        rm "$2"
fi